from os import environ
environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'

import pygame

DEFAULT_LOAD_ADDRESS = 0x0801

SYMBOLS = {
    'D6510': 0x0000,
    'R6510': 0x0001,
}

ROMSLIST = [
    # (File)Name, begin address, end address, bit of bank switch register (R6510)
    ("basic", 0xA000, 0xBFFF, 0),
    ("chargen", 0xD000, 0xDFFF, 1),
    ("kernal", 0xE000, 0xFFFF, 2),
]

COLORS = [0x000000,
          0xFFFFFF,
          0x93493E,
          0x85C6CD,
          0x9450B7,
          0x73B34A,
          0x4637AC,
          0xD6E07D,
          0x9A6929,
          0x675100,
          0xC28279,
          0x606060,
          0x8B8B8B,
          0xB4ED92,
          0x877BDF,
          0xB5B5B5
          ]

PALETTE = [[q >> 16, (q >> 8) & 0xFF, q & 0xFF] for q in COLORS]

ADDRESSING_METHODS = [
    "IMP",
    "IMM",
    "REL",
    "ABS",
    "ZP",
    "ABS_X",
    "ABS_Y",
    "ZP_X",
    "ZP_Y",
    "IND",
    "X_IND"
    "IND_Y"
]

OPCODES = {
    0x00: ("BRK", "IMP"),
    0x01: ("ORA", "X_IND"),
    0x02: (None, ""),
    0x03: (None, ""),
    0x04: ("NOP", "ZP"),
    0x05: ("ORA", "ZP"),
    0x06: ("ASL", "ZP"),
    0x07: (None, ""),
    0x08: ("PHP", "IMP"),
    0x09: ("ORA", "IMM"),
    0x0a: ("ASL", "IMP"),
    0x0b: (None, ""),
    0x0c: ("NOP", "ABS"),
    0x0d: ("ORA", "ABS"),
    0x0e: ("ASL", "ABS"),
    0x0f: (None, ""),

    0x10: ("BPL", "REL"),
    0x11: ("ORA", "IND_Y"),
    0x12: (None, ""),
    0x13: (None, ""),
    0x14: ("NOP", "ZP_X"),
    0x15: ("ORA", "ZP_X"),
    0x16: ("ASL", "ZP_X"),
    0x17: (None, ""),
    0x18: ("CLC", "IMP"),
    0x19: ("ORA", "ABS_Y"),
    0x1a: ("NOP", "IMP"),
    0x1b: (None, ""),
    0x1c: ("NOP", "ABS_X"),
    0x1d: ("ORA", "ABS_X"),
    0x1e: ("ASL", "ABS_X"),
    0x1f: (None, ""),

    0x20: ("JSR", "ABS"),
    0x21: ("AND", "X_IND"),
    0x22: (None, ""),
    0x23: (None, ""),
    0x24: ("BIT", "ZP"),
    0x25: ("AND", "ZP"),
    0x26: ("ROL", "ZP"),
    0x27: (None, ""),
    0x28: ("PLP", "IMP"),
    0x29: ("AND", "IMM"),
    0x2a: ("ROL", "IMP"),
    0x2b: ("ANC", "IMM"),
    0x2c: ("BIT", "ABS"),
    0x2d: ("AND", "ABS"),
    0x2e: ("ROL", "ABS"),
    0x2f: (None, ""),

    0x30: ("BMI", "REL"),
    0x31: ("AND", "IND_Y"),
    0x32: (None, ""),
    0x33: ("RLA", "IND_Y"),
    0x34: ("NOP", "ZP_X"),
    0x35: ("AND", "ZP_X"),
    0x36: ("ROL", "ZP_X"),
    0x37: (None, ""),
    0x38: ("SEC", "IMP"),
    0x39: ("AND", "ABS_Y"),
    0x3a: ("NOP", "IMP"),
    0x3b: ("RLA", "ABS_Y"),
    0x3c: ("NOP", "ABS_X"),
    0x3d: ("AND", "ABS_X"),
    0x3e: ("ROL", "ABS_X"),
    0x3f: (None, ""),

    0x40: ("RTI", "IMP"),
    0x41: ("EOR", "X_IND"),
    0x42: (None, ""),
    0x43: (None, ""),
    0x44: ("NOP", "ZP"),
    0x45: ("EOR", "ZP"),
    0x46: ("LSR", "ZP"),
    0x47: (None, ""),
    0x48: ("PHA", "IMP"),
    0x49: ("EOR", "IMM"),
    0x4a: ("LSR", "IMP"),
    0x4b: ("ALR", "IMM"),
    0x4c: ("JMP", "ABS"),
    0x4d: ("EOR", "ABS"),
    0x4e: ("LSR", "ABS"),
    0x4f: (None, ""),

    0x50: ("BVC", "REL"),
    0x51: ("EOR", "IND_Y"),
    0x52: (None, ""),
    0x53: (None, ""),
    0x54: ("NOP", "ZP_X"),
    0x55: ("EOR", "ZP_X"),
    0x56: ("LSR", "ZP_X"),
    0x57: (None, ""),
    0x58: ("CLI", "IMP"),
    0x59: ("EOR", "ABS_Y"),
    0x5a: ("NOP", "IMP"),
    0x5b: ("SRE", "ABS_Y"),
    0x5c: ("NOP", "ABS_X"),
    0x5d: ("EOR", "ABS_X"),
    0x5e: ("LSR", "ABS_X"),
    0x5f: (None, ""),

    0x60: ("RTS", "IMP"),
    0x61: ("ADC", "X_IND"),
    0x62: (None, ""),
    0x63: (None, ""),
    0x64: ("NOP", "ZP"),
    0x65: ("ADC", "ZP"),
    0x66: ("ROR", "ZP"),
    0x67: (None, ""),
    0x68: ("PLA", "IMP"),
    0x69: ("ADC", "IMM"),
    0x6a: ("ROR", "IMP"),
    0x6b: (None, ""),
    0x6c: ("JMP", "IND"),
    0x6d: ("ADC", "ABS"),
    0x6e: ("ROR", "ABS"),
    0x6f: (None, ""),

    0x70: ("BVS", "REL"),
    0x71: ("ADC", "IND_Y"),
    0x72: (None, ""),
    0x73: (None, ""),
    0x74: ("NOP", "ZP_X"),
    0x75: ("ADC", "ZP_X"),
    0x76: ("ROR", "ZP_X"),
    0x77: ("RRA", "ZP_X"),
    0x78: ("SEI", "IMP"),
    0x79: ("ADC", "ABS_Y"),
    0x7a: ("NOP", "IMP"),
    0x7b: (None, ""),
    0x7c: ("NOP", "ABS_X"),
    0x7d: ("ADC", "ABS_X"),
    0x7e: ("ROR", "ABS_X"),
    0x7f: (None, ""),

    0x80: ("NOP", "IMM"),
    0x81: ("STA", "X_IND"),
    0x82: (None, ""),
    0x83: (None, ""),
    0x84: ("STY", "ZP"),
    0x85: ("STA", "ZP"),
    0x86: ("STX", "ZP"),
    0x87: (None, ""),
    0x88: ("DEY", "IMP"),
    0x89: ("NOP", "IMM"),
    0x8a: ("TXA", "IMP"),
    0x8b: (None, ""),
    0x8c: ("STY", "ABS"),
    0x8d: ("STA", "ABS"),
    0x8e: ("STX", "ABS"),
    0x8f: (None, ""),

    0x90: ("BCC", "REL"),
    0x91: ("STA", "IND_Y"),
    0x92: (None, ""),
    0x93: (None, ""),
    0x94: ("STY", "ZP_X"),
    0x95: ("STA", "ZP_X"),
    0x96: ("STX", "ZP_Y"),
    0x97: (None, ""),
    0x98: ("TYA", "IMP"),
    0x99: ("STA", "ABS_Y"),
    0x9a: ("TXS", "IMP"),
    0x9b: (None, ""),
    0x9c: ("SHY", "ABS_X"),
    0x9d: ("STA", "ABS_X"),
    0x9e: ("SHX", "ABS_X"),
    0x9f: (None, ""),

    0xa0: ("LDY", "IMM"),
    0xa1: ("LDA", "X_IND"),
    0xa2: ("LDX", "IMM"),
    0xa3: (None, ""),
    0xa4: ("LDY", "ZP"),
    0xa5: ("LDA", "ZP"),
    0xa6: ("LDX", "ZP"),
    0xa7: (None, ""),
    0xa8: ("TAY", "IMP"),
    0xa9: ("LDA", "IMM"),
    0xaa: ("TAX", "IMP"),
    0xab: (None, ""),
    0xac: ("LDY", "ABS"),
    0xad: ("LDA", "ABS"),
    0xae: ("LDX", "ABS"),
    0xaf: (None, ""),

    0xb0: ("BCS", "REL"),
    0xb1: ("LDA", "IND_Y"),
    0xb2: (None, ""),
    0xb3: (None, ""),
    0xb4: ("LDY", "ZP_X"),
    0xb5: ("LDA", "ZP_X"),
    0xb6: ("LDX", "ZP_X"),
    0xb7: (None, ""),
    0xb8: ("CLV", "IMP"),
    0xb9: ("LDA", "ABS_Y"),
    0xba: ("TSX", "IMP"),
    0xbb: (None, ""),
    0xbc: ("LDY", "ABS_X"),
    0xbd: ("LDA", "ABS_X"),
    0xbe: ("LDX", "ABS_X"),
    0xbf: (None, ""),

    0xc0: ("CPY", "IMM"),
    0xc1: ("CMP", "X_IND"),
    0xc2: (None, ""),
    0xc3: (None, ""),
    0xc4: ("CPY", "ZP"),
    0xc5: ("CMP", "ZP"),
    0xc6: ("DEC", "ZP"),
    0xc7: (None, ""),
    0xc8: ("INY", "IMP"),
    0xc9: ("CMP", "IMM"),
    0xca: ("DEX", "IMP"),
    0xcb: (None, ""),
    0xcc: ("CPY", "ABS"),
    0xcd: ("CMP", "ABS"),
    0xce: ("DEC", "ABS"),
    0xcf: (None, ""),

    0xd0: ("BNE", "REL"),
    0xd1: ("CMP", "IND_Y"),
    0xd2: (None, ""),
    0xd3: (None, ""),
    0xd4: ("NOP", "ZP_X"),
    0xd5: ("CMP", "ZP_X"),
    0xd6: ("DEC", "ZP_X"),
    0xd7: (None, ""),
    0xd8: ("CLD", "IMP"),
    0xd9: ("CMP", "ABS_Y"),
    0xda: ("NOP", "IMP"),
    0xdb: (None, ""),
    0xdc: ("NOP", "IMM"),
    0xdd: ("CMP", "ABS_X"),
    0xde: ("DEC", "ABS_X"),
    0xdf: (None, ""),

    0xe0: ("CPX", "IMM"),
    0xe1: ("SBC", "X_IND"),
    0xe2: (None, ""),
    0xe3: (None, ""),
    0xe4: ("CPX", "ZP"),
    0xe5: ("SBC", "ZP"),
    0xe6: ("INC", "ZP"),
    0xe7: (None, ""),
    0xe8: ("INX", "IMP"),
    0xe9: ("SBC", "IMM"),
    0xea: ("NOP", "IMP"),
    0xeb: (None, ""),
    0xec: ("CPX", "ABS"),
    0xed: ("SBC", "ABS"),
    0xee: ("INC", "ABS"),
    0xef: (None, ""),

    0xf0: ("BEQ", "REL"),
    0xf1: ("SBC", "IND_Y"),
    0xf2: (None, ""),
    0xf3: (None, ""),
    0xf4: ("NOP", "ZP_X"),
    0xf5: ("SBC", "ZP_X"),
    0xf6: ("INC", "ZP_X"),
    0xf7: (None, ""),
    0xf8: ("SED", "IMP"),
    0xf9: ("SBC", "ABS_Y"),
    0xfa: ("NOP", "IMP"),
    0xfb: (None, ""),
    0xfc: ("NOP", "ABS_X"),
    0xfd: ("SBC", "ABS_X"),
    0xfe: ("INC", "ABS_X"),
    0xff: (None, ""),
}

KEYTABLE = {
    pygame.K_BACKSPACE   :[20, 148, 148]      ,
    #pygame.K_TAB         :[\t      ,
    #pygame.K_CLEAR       :[        ,
    pygame.K_RETURN      :[13, 141, 141] ,
    #pygame.K_PAUSE       :[        ,
    pygame.K_ESCAPE      :[3, 131, 131] ,
    pygame.K_SPACE       :[32, 160, 160],
#    pygame.K_EXCLAIM     :[33      ,
#    pygame.K_QUOTEDBL    :[34       ,
#    pygame.K_HASH        :[35       ,
#    pygame.K_DOLLAR      :[36       ,
#    pygame.K_AMPERSAND   :[38       ,
#    pygame.K_QUOTE       :[39        ,
#    pygame.K_LEFTPAREN   :[40       ,
#    pygame.K_RIGHTPAREN  :[41       ,
    pygame.K_ASTERISK    :[42 , None, None]      ,
    pygame.K_PLUS        :[43 , None, None]      ,
    pygame.K_COMMA       :[44 , None, None]      ,
    pygame.K_MINUS       :[45 , None, None]      ,
    pygame.K_PERIOD      :[46 , None, None]      ,
    pygame.K_SLASH       :[47 , None, None]      ,
    pygame.K_0           :[48 , None, None]    ,
    pygame.K_1           :[49 , None, 129]     ,
    pygame.K_2           :[50 , None, 149]    ,
    pygame.K_3           :[51 , None, 150]     ,
    pygame.K_4           :[52 , None, 151]    ,
    pygame.K_5           :[53 , None, 152]     ,
    pygame.K_6           :[54 , None, 153]     ,
    pygame.K_7           :[55 , None, 154]     ,
    pygame.K_8           :[56 , None, 155]     ,
    pygame.K_9           :[57 , None, None]     ,
    pygame.K_COLON       :[58 , None, None]    ,
    pygame.K_SEMICOLON   :[59 , None, None]    ,
    pygame.K_LESS        :[60 , None, None]     ,
    pygame.K_EQUALS      :[61 , None, None]     ,
    pygame.K_GREATER     :[63 , None, None]     ,
    pygame.K_QUESTION    :[63 , None, None]     ,
    pygame.K_AT          :[64 , None, None]     ,
    #pygame.K_LEFTBRACKET :[[       ,
    #pygame.K_BACKSLASH   :[\       ,
    #pygame.K_RIGHTBRACKET:[ ]      ,
    #pygame.K_CARET       :[^       ,
    #pygame.K_UNDERSCORE  :[_       ,
    #pygame.K_BACKQUOTE   :[`       ,
    pygame.K_a           :[65, 193, 176],
    pygame.K_b           :[66, 194, 191],
    pygame.K_c           :[67, 195, 188],
    pygame.K_d           :[68, 196, 172],
    pygame.K_e           :[69, 197, 177],
    pygame.K_f           :[70, 198, 187],
    pygame.K_g           :[71, 199, 165],
    pygame.K_h           :[72, 200, 180],
    pygame.K_i           :[73, 201, 162],
    pygame.K_j           :[74, 202, 181],
    pygame.K_k           :[75, 203, 161],
    pygame.K_l           :[76, 204, 182],
    pygame.K_m           :[77, 205, 167],
    pygame.K_n           :[78, 206, 170],
    pygame.K_o           :[79, 207, 185],
    pygame.K_p           :[80, 208, 175],
    pygame.K_q           :[81, 209, 171],
    pygame.K_r           :[82, 210, 178],
    pygame.K_s           :[83, 211, 174],
    pygame.K_t           :[84, 212, 163],
    pygame.K_u           :[85, 213, 184],
    pygame.K_v           :[86, 214, 190],
    pygame.K_w           :[87, 215, 179],
    pygame.K_x           :[88, 216, 188],
    pygame.K_y           :[89, 217, 183],
    pygame.K_z           :[90, 218, 173],
    pygame.K_DELETE      :[20, 148, 148],
    pygame.K_KP0         :[48, 48, 48],
    pygame.K_KP1         :[49, 49, 49],
    pygame.K_KP2         :[50 , 50, 50],
    pygame.K_KP3         :[51 , 51, 51],
    pygame.K_KP4         :[52 , 52, 52],
    pygame.K_KP5         :[53 , 53, 53],
    pygame.K_KP6         :[54 , 54, 54],
    pygame.K_KP7         :[55 , 55, 55],
    pygame.K_KP8         :[56 , 56, 56],
    pygame.K_KP9         :[57 , 57, 57],
    pygame.K_KP_PERIOD   :[46 , 46, 46],
    pygame.K_KP_DIVIDE   :[47 , 47, 47],
    pygame.K_KP_MULTIPLY :[42 , 42, 42],
    pygame.K_KP_MINUS    :[45 , 45, 45],
    pygame.K_KP_PLUS     :[43 , 43, 43],
    pygame.K_KP_ENTER    :[13 , 141, 141],
    pygame.K_KP_EQUALS   :[61 , None, None],
    pygame.K_UP          :[145, None, None],
    pygame.K_DOWN        :[17 , None, None],
    pygame.K_RIGHT       :[29 , None, None],
    pygame.K_LEFT        :[157, None, None],
    pygame.K_INSERT      :[148, 148, 148],
    pygame.K_HOME        :[19 , 147, 147],
    #pygame.K_END         :[        ,
    #pygame.K_PAGEUP      :[        ,
    #pygame.K_PAGEDOWN    :[        ,
    pygame.K_F1          :[133, 133, 133],
    pygame.K_F2          :[137, 137, 137],
    pygame.K_F3          :[134, 134, 134],
    pygame.K_F4          :[138, 138, 138],
    pygame.K_F5          :[135, 135, 135],
    pygame.K_F6          :[139, 139, 139],
    pygame.K_F7          :[136, 136, 136],
    pygame.K_F8          :[140, 140, 140],
    #pygame.K_F9          :[        ,
    #pygame.K_F10         :[        ,
    #pygame.K_F11         :[        ,
    #pygame.K_F12         :[        ,
    #pygame.K_F13         :[        ,
    #pygame.K_F14         :[        ,
    #pygame.K_F15         :[        ,
    #pygame.K_NUMLOCK     :[        ,
    #pygame.K_CAPSLOCK    :[        ,
    #pygame.K_SCROLLOCK   :[        ,
    #pygame.K_RSHIFT      :[        ,
    #pygame.K_LSHIFT      :[        ,
    #pygame.K_RCTRL       :[        ,
    #pygame.K_LCTRL       :[        ,
    #pygame.K_RALT        :[        ,
    #pygame.K_LALT        :[        ,
    #pygame.K_RMETA       :[        ,
    #pygame.K_LMETA       :[        ,
    #pygame.K_LSUPER      :[        ,
    #pygame.K_RSUPER      :[        ,
    #pygame.K_MODE        :[        ,
    #pygame.K_HELP        :[        ,
    #pygame.K_PRINT       :[        ,
    #pygame.K_SYSREQ      :[        ,
    #pygame.K_BREAK       :[        ,
    #pygame.K_MENU        :[        ,
    #pygame.K_POWER       :[        ,
    #pygame.K_EURO        :[        ,
}
KEYSCAN = {
    pygame.K_BACKSPACE   :  [0,0]    ,
    #pygame.K_TAB         :[\t      ,
    #pygame.K_CLEAR       :[        ,
    pygame.K_RETURN      : [0, 1],
    #pygame.K_PAUSE       :[        ,
    pygame.K_ESCAPE      : [7, 7],
    pygame.K_SPACE       : [7, 4],
#    pygame.K_EXCLAIM     :[33      ,
#    pygame.K_QUOTEDBL    :[34       ,
#    pygame.K_HASH        :[35       ,
#    pygame.K_DOLLAR      :[36       ,
#    pygame.K_AMPERSAND   :[38       ,
#    pygame.K_QUOTE       :[39        ,
#    pygame.K_LEFTPAREN   :[40       ,
#    pygame.K_RIGHTPAREN  :[41       ,
    pygame.K_ASTERISK    :[0,0]      ,
    pygame.K_PLUS        :[0,0]      ,
    pygame.K_COMMA       :[0,0]      ,
    pygame.K_MINUS       :[0,0]      ,
    pygame.K_PERIOD      :[0,0]      ,
    pygame.K_SLASH       :[0,0]      ,
    pygame.K_0           :[0,0]    ,
    pygame.K_1           :[0,0]     ,
    pygame.K_2           :[0,0]    ,
    pygame.K_3           :[0,0]     ,
    pygame.K_4           :[0,0]    ,
    pygame.K_5           :[0,0]     ,
    pygame.K_6           :[0,0]     ,
    pygame.K_7           :[0,0]     ,
    pygame.K_8           :[0,0]     ,
    pygame.K_9           :[0,0]     ,
    pygame.K_COLON       :[0,0]    ,
    pygame.K_SEMICOLON   :[0,0]    ,
    pygame.K_LESS        :[0,0]     ,
    pygame.K_EQUALS      :[0,0]     ,
    pygame.K_GREATER     :[0,0]     ,
    pygame.K_QUESTION    :[0,0]     ,
    pygame.K_AT          :[0,0]     ,
    #pygame.K_LEFTBRACKET :[0,0][[       ,
    #pygame.K_BACKSLASH   :[0,0][\       ,
    #pygame.K_RIGHTBRACKET:[0,0]      ,
    #pygame.K_CARET       :[0,0][^       ,
    #pygame.K_UNDERSCORE  :[0,0][_       ,
    #pygame.K_BACKQUOTE   :[0,0][`       ,
    pygame.K_a           :[1,2],
    pygame.K_b           :[3,4],
    pygame.K_c           :[2,4],
    pygame.K_d           :[0,0],
    pygame.K_e           :[0,0],
    pygame.K_f           :[0,0],
    pygame.K_g           :[0,0],
    pygame.K_h           :[0,0],
    pygame.K_i           :[0,0],
    pygame.K_j           :[0,0],
    pygame.K_k           :[0,0],
    pygame.K_l           :[0,0],
    pygame.K_m           :[0,0],
    pygame.K_n           :[0,0],
    pygame.K_o           :[0,0],
    pygame.K_p           :[0,0],
    pygame.K_q           :[0,0],
    pygame.K_r           :[0,0],
    pygame.K_s           :[0,0],
    pygame.K_t           :[0,0],
    pygame.K_u           :[0,0],
    pygame.K_v           :[0,0],
    pygame.K_w           :[0,0],
    pygame.K_x           :[0,0],
    pygame.K_y           :[0,0],
    pygame.K_z           :[0,0],
    pygame.K_DELETE      :[0,0],
    pygame.K_KP0         :[0,0],
    pygame.K_KP1         :[0,0],
    pygame.K_KP2         :[0,0],
    pygame.K_KP3         :[0,0],
    pygame.K_KP4         :[0,0],
    pygame.K_KP5         :[0,0],
    pygame.K_KP6         :[0,0],
    pygame.K_KP7         :[0,0],
    pygame.K_KP8         :[0,0],
    pygame.K_KP9         :[0,0],
    pygame.K_KP_PERIOD   :[0,0],
    pygame.K_KP_DIVIDE   :[0,0],
    pygame.K_KP_MULTIPLY :[0,0],
    pygame.K_KP_MINUS    :[0,0],
    pygame.K_KP_PLUS     :[0,0],
    pygame.K_KP_ENTER    :[0,0],
    pygame.K_KP_EQUALS   :[0,0],
    pygame.K_UP          :[0,0],
    pygame.K_DOWN        :[0,0],
    pygame.K_RIGHT       :[0,0],
    pygame.K_LEFT        :[0,0],
    pygame.K_INSERT      :[0,0],
    pygame.K_HOME        :[0,0],
    #pygame.K_END         :[0,0][        ,
    #pygame.K_PAGEUP      :[0,0][        ,
    #pygame.K_PAGEDOWN    :[0,0][        ,
    pygame.K_F1          :[0,0],
    pygame.K_F2          :[0,0],
    pygame.K_F3          :[0,0],
    pygame.K_F4          :[0,0],
    pygame.K_F5          :[0,0],
    pygame.K_F6          :[0,0],
    pygame.K_F7          :[0,0],
    pygame.K_F8          :[0,0],
    #pygame.K_F9          :[        ,
    #pygame.K_F10         :[        ,
    #pygame.K_F11         :[        ,
    #pygame.K_F12         :[        ,
    #pygame.K_F13         :[        ,
    #pygame.K_F14         :[        ,
    #pygame.K_F15         :[        ,
    #pygame.K_NUMLOCK     :[        ,
    #pygame.K_CAPSLOCK    :[        ,
    #pygame.K_SCROLLOCK   :[        ,
    #pygame.K_RSHIFT      :[        ,
    #pygame.K_LSHIFT      :[        ,
    #pygame.K_RCTRL       :[        ,
    #pygame.K_LCTRL       :[        ,
    #pygame.K_RALT        :[        ,
    #pygame.K_LALT        :[        ,
    #pygame.K_RMETA       :[        ,
    #pygame.K_LMETA       :[        ,
    #pygame.K_LSUPER      :[        ,
    #pygame.K_RSUPER      :[        ,
    #pygame.K_MODE        :[        ,
    #pygame.K_HELP        :[        ,
    #pygame.K_PRINT       :[        ,
    #pygame.K_SYSREQ      :[        ,
    #pygame.K_BREAK       :[        ,
    #pygame.K_MENU        :[        ,
    #pygame.K_POWER       :[        ,
    #pygame.K_EURO        :[        ,

}
